providers = ["node"]

[variables]
  NODE_ENV = "production"

[phases.setup]
  nixPkgs = ["nodejs_20"]

[phases.install]
  # Używamy pnpm, który lepiej radzi sobie z zależnościami
  cmds = ["pnpm install"]

[phases.build]
  # Wystarczy `npm run build`, bo `nuxt prepare` uruchomi się automatycznie po instalacji
  cmds = ["npm run build"]

[phases.start]
  # Poprawiony klucz z `cmd` na `startCmd`
  startCmd = "node .output/server/index.mjs"