# nixpacks.toml

[phases.setup]
  # Instalujemy Node.js w wersji 20 oraz pnpm
  nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
  # Używamy pnpm do instalacji zależności
  cmds = ["pnpm install"]

[phases.build]
  # Budujemy aplikację
  cmds = ["pnpm run build"]

[phases.start]
  # Uruchamiamy serwer produkcyjny
  startCmd = "node .output/server/index.mjs"