providers = ["node"]

[variables]
  NODE_ENV = "production"

[setup]
  nixPkgs = ["nodejs_20"]

# Faza instalacji jest obsługiwana automatycznie przez providera node,
# ale dla jasności można ją zostawić.
[install]
  cmds = ["pnpm install"]

# Faza budowania aplikacji
[build]
  cmds = ["npm run prepare", "npm run build"]

# Faza uruchomienia gotowej aplikacji
[start]
cmd = 'node .output/server/index.mjs'