<template>
  <div v-if="body" v-html="renderedHtml" class="prose max-w-none"></div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'

// Props
const props = defineProps<{ body: string | null | undefined }>()

// i18n locale (aby prze-renderować przy zmianie języka)
const { locale } = useI18n()

// Reaktywne źródła danych do obserwacji
const safeBody = computed(() => props.body || '')

// SSR-friendly render via server API with caching
// Używamy reaktywnego klucza zależnego od treści i języka, aby uniknąć starych danych po przełączeniu języka
const { data } = await useAsyncData(
  () => `richtext-render-${locale.value}-${safeBody.value.length}-${safeBody.value.slice(0, 16)}`,
  () => $fetch<{ html: string }>('/api/render-md', {
    method: 'POST',
    body: { body: safeBody.value }
  })
)

const renderedHtml = computed(() => data.value?.html || '')

</script>

<style>
@reference '../../../assets/css/main.css';
/* Style dla podświetlania składni Shiki */
/* Możesz dostosować te style lub użyć gotowych motywów */

.shiki {
  background-color: #212529 !important; /* Ciemne tło dla bloku kodu */
  padding: 1em;
  border-radius: 0.5em;
  overflow-x: auto;
}

.prose h1, .prose h2, .prose h3, .prose h4, .prose h5, .prose h6, .prose p, .prose ul, .prose ol, .prose li, .prose figure, .prose blockquote, .prose pre {
	@apply my-1;
}
.prose h1{
	@apply text-6xl;
}

.prose h2{
	@apply text-4xl;
}

.prose h3{
	@apply text-2xl;
}

.prose h4{
	@apply text-xl;
}

.prose h5{
	@apply text-lg;
}

.prose h6{
	@apply text-base ;
}

.prose p{
	@apply text-lg;
}

.timeline-right > .prose p {
	@apply text-sm
}

.prose table {
	@apply overflow-hidden sm:rounded-lg w-full text-sm text-left rtl:text-right text-gray-400;
}

.prose table > thead {
	@apply text-xs  uppercase bg-[#2e353b] text-gray-400;
}

.prose table > thead > tr > th {
	@apply px-6 py-3;
}


.prose table > tbody > tr {
	@apply border-b bg-[#212529] border-[#2e353b] hover:bg-[#272e35] duration-300;
}

.prose table > tbody > tr > th {
	@apply px-6 py-4 font-medium whitespace-nowrap text-white;
}


.prose table > tbody > tr > td {
	@apply px-6 py-4;
}

.prose > p > code{
	@apply bg-slate-700/50 rounded-sm px-1;
}

.prose > p > mark {
	@apply bg-sky-300
}

.prose kbd{
	@apply bg-slate-700/50 rounded-sm px-1;
}


.prose ul {
	@apply list-disc list-inside marker:text-sky-400;
}

.prose ul > li > ul {
	@apply pl-3 list-disc list-inside marker:text-sky-400;
}

.prose ul > li > ol {
	@apply pl-3 list-decimal list-inside marker:text-sky-400;
}

.prose ol {
	@apply list-decimal list-inside marker:text-sky-400;
}

.prose ol > li > ol{
	@apply pl-3 list-decimal list-inside marker:text-sky-400;
}

.prose ol > li > ul {
	@apply pl-3 list-disc list-inside marker:text-sky-400;
}

.prose blockquote {
	@apply bg-slate-700/30 px-4 py-1 rounded-lg w-fit;
}

.prose a {
  @apply text-sky-600 hover:underline;
}

.prose hr {
	@apply border-slate-700;
}



/* Task lists (generated by markdown-it-task-lists) */
.prose ul.task-list {
  list-style: none;
  padding-left: 0;
}

.prose li.task-list-item {
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.prose li.task-list-item input[type="checkbox"] {
  margin: 0 0.25rem 0 0.1rem;
  width: 1rem;
  height: 1rem;
  accent-color: rgb(2 132 199) !important; /* tailwind sky-600 */
}

.prose li.task-list-item input[type="checkbox"][disabled] {
  cursor: default;
  opacity: 0.9;
}
</style>